### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Akkey57492** [2lstudios-mc/FlamePaper#19] opened 2021-12-11 20:26 UTC
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.lang.ExceptionInInitializerError
        at org.bukkit.craftbukkit.Main.main(Main.java:201)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at net.minecraft.server.v1_8_R3.MinecraftServer.<clinit>(MinecraftServer.java:53)
        ... 1 more
```
I get an error when starting and cannot start.
When I run it with JRE8, I get the following error.
```
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```

**Comment by xIsm4** [comment] 2021-12-11 22:22
Update to lastest build @Akkey57492.

**Comment by linsaftw** [comment] 2021-12-11 22:24
This was fixed on 2a5099a please update. Reopen if the error persists.

**Closed by linsaftw** 2021-12-11 22:24 UTC

**Comment by Akkey57492** [comment] 2021-12-11 23:41
I'm getting an error at 2a5099a!

**Comment by Akkey57492** [comment] 2021-12-11 23:42
@linsaftw 
The error also occurs with 2a5099a. Or rather, I got the error with 2a5099a.

**Comment by linsaftw** [comment] 2021-12-12 01:56
You are trying to run Minecraft 1.8 with Java version prior to 8. Make sure to use Java 8.

**Comment by Akkey57492** [comment] 2021-12-12 08:03
I am also getting the error in Java 8.
It is described in the first message.
(By the way, I have good memory, and Spigot mackerel works well with JRE8.)

**Comment by linsaftw** [comment] 2021-12-12 12:49
`Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap`

This means you don't have 2gb available on your machine, an error by the java virtual machine.

Are you having this error or the other one you reported? Can you send the full log with hastebin?

**Comment by linsaftw** [comment] 2021-12-12 15:09
Hello please try latest release c92dafe

**Comment by Akkey57492** [comment] 2021-12-12 21:40
I still get the same error, even with JRE8.
```
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```
I'm getting the same error.

**Comment by linsaftw** [comment] 2021-12-12 21:46
> I still get the same error, even with JRE8.
> 
> ```
> Error occurred during initialization of VM
> Could not reserve enough space for 2097152KB object heap
> ```
> 
> I'm getting the same error.

How much ram does your system have?

**Comment by Akkey57492** [comment] 2021-12-12 22:12
16GB

**Comment by Akkey57492** [comment] 2021-12-12 22:13
I specified 2G.

**Comment by linsaftw** [comment] 2021-12-12 22:19
This is weird, the error is 100% from the JVM. We can't do anything, it doesn't come from FlamePaper. Try restarting the machine.

**Comment by Akkey57492** [comment] 2021-12-12 22:48
I understand. Also, this is an opinion... I'd like to ask if it's possible to support arm cpu? (Because I want to run it on a Raspberry Pi).

**Comment by Akkey57492** [comment] 2021-12-12 22:52
I restarted my PC and got the same error.
I don't know the cause at all (´;ω;´).

**Comment by Akkey57492** [comment] 2021-12-12 23:01
I was able to do it after a solid install of 64bit Java from Oracle! (It worked with 2GB of FlameCord!).

**Comment by linsaftw** [comment] 2021-12-12 23:50
> I understand. Also, this is an opinion... I'd like to ask if it's possible to support arm cpu? (Because I want to run it on a Raspberry Pi).

Not sure. The problem is not Spigot but it's dependencies.

> I was able to do it after a solid install of 64bit Java from Oracle! (It worked with 2GB of FlameCord!).

I am glad that solved it!

**Comment by TheJoshue** [comment] 2021-12-29 13:47
> Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap

Is your OS (Windows or whatever you're using) 32bit?
